/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (https://www.swig.org).
 * Version 4.1.1
 *
 * Do not make changes to this file unless you know what you are doing - modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package com.quickhot.ctp.api;

public class CThostFtdcCFMMCBrokerKeyField {
  private transient long swigCPtr;
  protected transient boolean swigCMemOwn;

  protected CThostFtdcCFMMCBrokerKeyField(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(CThostFtdcCFMMCBrokerKeyField obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected static long swigRelease(CThostFtdcCFMMCBrokerKeyField obj) {
    long ptr = 0;
    if (obj != null) {
      if (!obj.swigCMemOwn)
        throw new RuntimeException("Cannot release ownership as memory is not owned");
      ptr = obj.swigCPtr;
      obj.swigCMemOwn = false;
      obj.delete();
    }
    return ptr;
  }

  @SuppressWarnings("deprecation")
  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        thosttraderapiJNI.delete_CThostFtdcCFMMCBrokerKeyField(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public void setBrokerID(String value) {
    thosttraderapiJNI.CThostFtdcCFMMCBrokerKeyField_BrokerID_set(swigCPtr, this, value);
  }

  public String getBrokerID() {
    return thosttraderapiJNI.CThostFtdcCFMMCBrokerKeyField_BrokerID_get(swigCPtr, this);
  }

  public void setParticipantID(String value) {
    thosttraderapiJNI.CThostFtdcCFMMCBrokerKeyField_ParticipantID_set(swigCPtr, this, value);
  }

  public String getParticipantID() {
    return thosttraderapiJNI.CThostFtdcCFMMCBrokerKeyField_ParticipantID_get(swigCPtr, this);
  }

  public void setCreateDate(String value) {
    thosttraderapiJNI.CThostFtdcCFMMCBrokerKeyField_CreateDate_set(swigCPtr, this, value);
  }

  public String getCreateDate() {
    return thosttraderapiJNI.CThostFtdcCFMMCBrokerKeyField_CreateDate_get(swigCPtr, this);
  }

  public void setCreateTime(String value) {
    thosttraderapiJNI.CThostFtdcCFMMCBrokerKeyField_CreateTime_set(swigCPtr, this, value);
  }

  public String getCreateTime() {
    return thosttraderapiJNI.CThostFtdcCFMMCBrokerKeyField_CreateTime_get(swigCPtr, this);
  }

  public void setKeyID(int value) {
    thosttraderapiJNI.CThostFtdcCFMMCBrokerKeyField_KeyID_set(swigCPtr, this, value);
  }

  public int getKeyID() {
    return thosttraderapiJNI.CThostFtdcCFMMCBrokerKeyField_KeyID_get(swigCPtr, this);
  }

  public void setCurrentKey(String value) {
    thosttraderapiJNI.CThostFtdcCFMMCBrokerKeyField_CurrentKey_set(swigCPtr, this, value);
  }

  public String getCurrentKey() {
    return thosttraderapiJNI.CThostFtdcCFMMCBrokerKeyField_CurrentKey_get(swigCPtr, this);
  }

  public void setKeyKind(char value) {
    thosttraderapiJNI.CThostFtdcCFMMCBrokerKeyField_KeyKind_set(swigCPtr, this, value);
  }

  public char getKeyKind() {
    return thosttraderapiJNI.CThostFtdcCFMMCBrokerKeyField_KeyKind_get(swigCPtr, this);
  }

  public CThostFtdcCFMMCBrokerKeyField() {
    this(thosttraderapiJNI.new_CThostFtdcCFMMCBrokerKeyField(), true);
  }

}
