/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (https://www.swig.org).
 * Version 4.1.1
 *
 * Do not make changes to this file unless you know what you are doing - modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package com.quickhot.ctp.api;

public class CThostFtdcSPBMOptionParameterField {
  private transient long swigCPtr;
  protected transient boolean swigCMemOwn;

  protected CThostFtdcSPBMOptionParameterField(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(CThostFtdcSPBMOptionParameterField obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected static long swigRelease(CThostFtdcSPBMOptionParameterField obj) {
    long ptr = 0;
    if (obj != null) {
      if (!obj.swigCMemOwn)
        throw new RuntimeException("Cannot release ownership as memory is not owned");
      ptr = obj.swigCPtr;
      obj.swigCMemOwn = false;
      obj.delete();
    }
    return ptr;
  }

  @SuppressWarnings("deprecation")
  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        thosttraderapiJNI.delete_CThostFtdcSPBMOptionParameterField(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public void setTradingDay(String value) {
    thosttraderapiJNI.CThostFtdcSPBMOptionParameterField_TradingDay_set(swigCPtr, this, value);
  }

  public String getTradingDay() {
    return thosttraderapiJNI.CThostFtdcSPBMOptionParameterField_TradingDay_get(swigCPtr, this);
  }

  public void setExchangeID(String value) {
    thosttraderapiJNI.CThostFtdcSPBMOptionParameterField_ExchangeID_set(swigCPtr, this, value);
  }

  public String getExchangeID() {
    return thosttraderapiJNI.CThostFtdcSPBMOptionParameterField_ExchangeID_get(swigCPtr, this);
  }

  public void setInstrumentID(String value) {
    thosttraderapiJNI.CThostFtdcSPBMOptionParameterField_InstrumentID_set(swigCPtr, this, value);
  }

  public String getInstrumentID() {
    return thosttraderapiJNI.CThostFtdcSPBMOptionParameterField_InstrumentID_get(swigCPtr, this);
  }

  public void setProdFamilyCode(String value) {
    thosttraderapiJNI.CThostFtdcSPBMOptionParameterField_ProdFamilyCode_set(swigCPtr, this, value);
  }

  public String getProdFamilyCode() {
    return thosttraderapiJNI.CThostFtdcSPBMOptionParameterField_ProdFamilyCode_get(swigCPtr, this);
  }

  public void setCvf(int value) {
    thosttraderapiJNI.CThostFtdcSPBMOptionParameterField_Cvf_set(swigCPtr, this, value);
  }

  public int getCvf() {
    return thosttraderapiJNI.CThostFtdcSPBMOptionParameterField_Cvf_get(swigCPtr, this);
  }

  public void setDownPrice(double value) {
    thosttraderapiJNI.CThostFtdcSPBMOptionParameterField_DownPrice_set(swigCPtr, this, value);
  }

  public double getDownPrice() {
    return thosttraderapiJNI.CThostFtdcSPBMOptionParameterField_DownPrice_get(swigCPtr, this);
  }

  public void setDelta(double value) {
    thosttraderapiJNI.CThostFtdcSPBMOptionParameterField_Delta_set(swigCPtr, this, value);
  }

  public double getDelta() {
    return thosttraderapiJNI.CThostFtdcSPBMOptionParameterField_Delta_get(swigCPtr, this);
  }

  public void setSlimiDelta(double value) {
    thosttraderapiJNI.CThostFtdcSPBMOptionParameterField_SlimiDelta_set(swigCPtr, this, value);
  }

  public double getSlimiDelta() {
    return thosttraderapiJNI.CThostFtdcSPBMOptionParameterField_SlimiDelta_get(swigCPtr, this);
  }

  public void setPreSettlementPrice(double value) {
    thosttraderapiJNI.CThostFtdcSPBMOptionParameterField_PreSettlementPrice_set(swigCPtr, this, value);
  }

  public double getPreSettlementPrice() {
    return thosttraderapiJNI.CThostFtdcSPBMOptionParameterField_PreSettlementPrice_get(swigCPtr, this);
  }

  public CThostFtdcSPBMOptionParameterField() {
    this(thosttraderapiJNI.new_CThostFtdcSPBMOptionParameterField(), true);
  }

}
