/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (https://www.swig.org).
 * Version 4.1.1
 *
 * Do not make changes to this file unless you know what you are doing - modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package com.quickhot.ctp.api;

public class CThostFtdcSyncDeltaOptExchMarginField {
  private transient long swigCPtr;
  protected transient boolean swigCMemOwn;

  protected CThostFtdcSyncDeltaOptExchMarginField(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(CThostFtdcSyncDeltaOptExchMarginField obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected static long swigRelease(CThostFtdcSyncDeltaOptExchMarginField obj) {
    long ptr = 0;
    if (obj != null) {
      if (!obj.swigCMemOwn)
        throw new RuntimeException("Cannot release ownership as memory is not owned");
      ptr = obj.swigCPtr;
      obj.swigCMemOwn = false;
      obj.delete();
    }
    return ptr;
  }

  @SuppressWarnings("deprecation")
  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        thosttraderapiJNI.delete_CThostFtdcSyncDeltaOptExchMarginField(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public void setBrokerID(String value) {
    thosttraderapiJNI.CThostFtdcSyncDeltaOptExchMarginField_BrokerID_set(swigCPtr, this, value);
  }

  public String getBrokerID() {
    return thosttraderapiJNI.CThostFtdcSyncDeltaOptExchMarginField_BrokerID_get(swigCPtr, this);
  }

  public void setInstrumentID(String value) {
    thosttraderapiJNI.CThostFtdcSyncDeltaOptExchMarginField_InstrumentID_set(swigCPtr, this, value);
  }

  public String getInstrumentID() {
    return thosttraderapiJNI.CThostFtdcSyncDeltaOptExchMarginField_InstrumentID_get(swigCPtr, this);
  }

  public void setSShortMarginRatioByMoney(double value) {
    thosttraderapiJNI.CThostFtdcSyncDeltaOptExchMarginField_SShortMarginRatioByMoney_set(swigCPtr, this, value);
  }

  public double getSShortMarginRatioByMoney() {
    return thosttraderapiJNI.CThostFtdcSyncDeltaOptExchMarginField_SShortMarginRatioByMoney_get(swigCPtr, this);
  }

  public void setSShortMarginRatioByVolume(double value) {
    thosttraderapiJNI.CThostFtdcSyncDeltaOptExchMarginField_SShortMarginRatioByVolume_set(swigCPtr, this, value);
  }

  public double getSShortMarginRatioByVolume() {
    return thosttraderapiJNI.CThostFtdcSyncDeltaOptExchMarginField_SShortMarginRatioByVolume_get(swigCPtr, this);
  }

  public void setHShortMarginRatioByMoney(double value) {
    thosttraderapiJNI.CThostFtdcSyncDeltaOptExchMarginField_HShortMarginRatioByMoney_set(swigCPtr, this, value);
  }

  public double getHShortMarginRatioByMoney() {
    return thosttraderapiJNI.CThostFtdcSyncDeltaOptExchMarginField_HShortMarginRatioByMoney_get(swigCPtr, this);
  }

  public void setHShortMarginRatioByVolume(double value) {
    thosttraderapiJNI.CThostFtdcSyncDeltaOptExchMarginField_HShortMarginRatioByVolume_set(swigCPtr, this, value);
  }

  public double getHShortMarginRatioByVolume() {
    return thosttraderapiJNI.CThostFtdcSyncDeltaOptExchMarginField_HShortMarginRatioByVolume_get(swigCPtr, this);
  }

  public void setAShortMarginRatioByMoney(double value) {
    thosttraderapiJNI.CThostFtdcSyncDeltaOptExchMarginField_AShortMarginRatioByMoney_set(swigCPtr, this, value);
  }

  public double getAShortMarginRatioByMoney() {
    return thosttraderapiJNI.CThostFtdcSyncDeltaOptExchMarginField_AShortMarginRatioByMoney_get(swigCPtr, this);
  }

  public void setAShortMarginRatioByVolume(double value) {
    thosttraderapiJNI.CThostFtdcSyncDeltaOptExchMarginField_AShortMarginRatioByVolume_set(swigCPtr, this, value);
  }

  public double getAShortMarginRatioByVolume() {
    return thosttraderapiJNI.CThostFtdcSyncDeltaOptExchMarginField_AShortMarginRatioByVolume_get(swigCPtr, this);
  }

  public void setMShortMarginRatioByMoney(double value) {
    thosttraderapiJNI.CThostFtdcSyncDeltaOptExchMarginField_MShortMarginRatioByMoney_set(swigCPtr, this, value);
  }

  public double getMShortMarginRatioByMoney() {
    return thosttraderapiJNI.CThostFtdcSyncDeltaOptExchMarginField_MShortMarginRatioByMoney_get(swigCPtr, this);
  }

  public void setMShortMarginRatioByVolume(double value) {
    thosttraderapiJNI.CThostFtdcSyncDeltaOptExchMarginField_MShortMarginRatioByVolume_set(swigCPtr, this, value);
  }

  public double getMShortMarginRatioByVolume() {
    return thosttraderapiJNI.CThostFtdcSyncDeltaOptExchMarginField_MShortMarginRatioByVolume_get(swigCPtr, this);
  }

  public void setActionDirection(char value) {
    thosttraderapiJNI.CThostFtdcSyncDeltaOptExchMarginField_ActionDirection_set(swigCPtr, this, value);
  }

  public char getActionDirection() {
    return thosttraderapiJNI.CThostFtdcSyncDeltaOptExchMarginField_ActionDirection_get(swigCPtr, this);
  }

  public void setSyncDeltaSequenceNo(int value) {
    thosttraderapiJNI.CThostFtdcSyncDeltaOptExchMarginField_SyncDeltaSequenceNo_set(swigCPtr, this, value);
  }

  public int getSyncDeltaSequenceNo() {
    return thosttraderapiJNI.CThostFtdcSyncDeltaOptExchMarginField_SyncDeltaSequenceNo_get(swigCPtr, this);
  }

  public CThostFtdcSyncDeltaOptExchMarginField() {
    this(thosttraderapiJNI.new_CThostFtdcSyncDeltaOptExchMarginField(), true);
  }

}
