/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (https://www.swig.org).
 * Version 4.1.1
 *
 * Do not make changes to this file unless you know what you are doing - modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package com.quickhot.ctp.api;

public class CThostFtdcSyncDeltaProductStatusField {
  private transient long swigCPtr;
  protected transient boolean swigCMemOwn;

  protected CThostFtdcSyncDeltaProductStatusField(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(CThostFtdcSyncDeltaProductStatusField obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected static long swigRelease(CThostFtdcSyncDeltaProductStatusField obj) {
    long ptr = 0;
    if (obj != null) {
      if (!obj.swigCMemOwn)
        throw new RuntimeException("Cannot release ownership as memory is not owned");
      ptr = obj.swigCPtr;
      obj.swigCMemOwn = false;
      obj.delete();
    }
    return ptr;
  }

  @SuppressWarnings("deprecation")
  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        thosttraderapiJNI.delete_CThostFtdcSyncDeltaProductStatusField(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public void setSyncDeltaSequenceNo(int value) {
    thosttraderapiJNI.CThostFtdcSyncDeltaProductStatusField_SyncDeltaSequenceNo_set(swigCPtr, this, value);
  }

  public int getSyncDeltaSequenceNo() {
    return thosttraderapiJNI.CThostFtdcSyncDeltaProductStatusField_SyncDeltaSequenceNo_get(swigCPtr, this);
  }

  public void setExchangeID(String value) {
    thosttraderapiJNI.CThostFtdcSyncDeltaProductStatusField_ExchangeID_set(swigCPtr, this, value);
  }

  public String getExchangeID() {
    return thosttraderapiJNI.CThostFtdcSyncDeltaProductStatusField_ExchangeID_get(swigCPtr, this);
  }

  public void setProductID(String value) {
    thosttraderapiJNI.CThostFtdcSyncDeltaProductStatusField_ProductID_set(swigCPtr, this, value);
  }

  public String getProductID() {
    return thosttraderapiJNI.CThostFtdcSyncDeltaProductStatusField_ProductID_get(swigCPtr, this);
  }

  public void setProductStatus(char value) {
    thosttraderapiJNI.CThostFtdcSyncDeltaProductStatusField_ProductStatus_set(swigCPtr, this, value);
  }

  public char getProductStatus() {
    return thosttraderapiJNI.CThostFtdcSyncDeltaProductStatusField_ProductStatus_get(swigCPtr, this);
  }

  public CThostFtdcSyncDeltaProductStatusField() {
    this(thosttraderapiJNI.new_CThostFtdcSyncDeltaProductStatusField(), true);
  }

}
