/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (https://www.swig.org).
 * Version 4.1.1
 *
 * Do not make changes to this file unless you know what you are doing - modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package com.quickhot.ctp.api;

public class CThostFtdcFrontStatusField {
  private transient long swigCPtr;
  protected transient boolean swigCMemOwn;

  protected CThostFtdcFrontStatusField(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(CThostFtdcFrontStatusField obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected static long swigRelease(CThostFtdcFrontStatusField obj) {
    long ptr = 0;
    if (obj != null) {
      if (!obj.swigCMemOwn)
        throw new RuntimeException("Cannot release ownership as memory is not owned");
      ptr = obj.swigCPtr;
      obj.swigCMemOwn = false;
      obj.delete();
    }
    return ptr;
  }

  @SuppressWarnings("deprecation")
  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        thosttraderapiJNI.delete_CThostFtdcFrontStatusField(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public void setFrontID(int value) {
    thosttraderapiJNI.CThostFtdcFrontStatusField_FrontID_set(swigCPtr, this, value);
  }

  public int getFrontID() {
    return thosttraderapiJNI.CThostFtdcFrontStatusField_FrontID_get(swigCPtr, this);
  }

  public void setLastReportDate(String value) {
    thosttraderapiJNI.CThostFtdcFrontStatusField_LastReportDate_set(swigCPtr, this, value);
  }

  public String getLastReportDate() {
    return thosttraderapiJNI.CThostFtdcFrontStatusField_LastReportDate_get(swigCPtr, this);
  }

  public void setLastReportTime(String value) {
    thosttraderapiJNI.CThostFtdcFrontStatusField_LastReportTime_set(swigCPtr, this, value);
  }

  public String getLastReportTime() {
    return thosttraderapiJNI.CThostFtdcFrontStatusField_LastReportTime_get(swigCPtr, this);
  }

  public void setIsActive(int value) {
    thosttraderapiJNI.CThostFtdcFrontStatusField_IsActive_set(swigCPtr, this, value);
  }

  public int getIsActive() {
    return thosttraderapiJNI.CThostFtdcFrontStatusField_IsActive_get(swigCPtr, this);
  }

  public CThostFtdcFrontStatusField() {
    this(thosttraderapiJNI.new_CThostFtdcFrontStatusField(), true);
  }

}
