/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (https://www.swig.org).
 * Version 4.1.1
 *
 * Do not make changes to this file unless you know what you are doing - modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package com.quickhot.ctp.api;

public class CThostFtdcQrySPBMInterParameterField {
  private transient long swigCPtr;
  protected transient boolean swigCMemOwn;

  protected CThostFtdcQrySPBMInterParameterField(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(CThostFtdcQrySPBMInterParameterField obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected static long swigRelease(CThostFtdcQrySPBMInterParameterField obj) {
    long ptr = 0;
    if (obj != null) {
      if (!obj.swigCMemOwn)
        throw new RuntimeException("Cannot release ownership as memory is not owned");
      ptr = obj.swigCPtr;
      obj.swigCMemOwn = false;
      obj.delete();
    }
    return ptr;
  }

  @SuppressWarnings("deprecation")
  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        thosttraderapiJNI.delete_CThostFtdcQrySPBMInterParameterField(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public void setExchangeID(String value) {
    thosttraderapiJNI.CThostFtdcQrySPBMInterParameterField_ExchangeID_set(swigCPtr, this, value);
  }

  public String getExchangeID() {
    return thosttraderapiJNI.CThostFtdcQrySPBMInterParameterField_ExchangeID_get(swigCPtr, this);
  }

  public void setLeg1ProdFamilyCode(String value) {
    thosttraderapiJNI.CThostFtdcQrySPBMInterParameterField_Leg1ProdFamilyCode_set(swigCPtr, this, value);
  }

  public String getLeg1ProdFamilyCode() {
    return thosttraderapiJNI.CThostFtdcQrySPBMInterParameterField_Leg1ProdFamilyCode_get(swigCPtr, this);
  }

  public void setLeg2ProdFamilyCode(String value) {
    thosttraderapiJNI.CThostFtdcQrySPBMInterParameterField_Leg2ProdFamilyCode_set(swigCPtr, this, value);
  }

  public String getLeg2ProdFamilyCode() {
    return thosttraderapiJNI.CThostFtdcQrySPBMInterParameterField_Leg2ProdFamilyCode_get(swigCPtr, this);
  }

  public CThostFtdcQrySPBMInterParameterField() {
    this(thosttraderapiJNI.new_CThostFtdcQrySPBMInterParameterField(), true);
  }

}
