/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (https://www.swig.org).
 * Version 4.1.1
 *
 * Do not make changes to this file unless you know what you are doing - modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package com.quickhot.ctp.api;

public class CThostFtdcSPBMFutureParameterField {
  private transient long swigCPtr;
  protected transient boolean swigCMemOwn;

  protected CThostFtdcSPBMFutureParameterField(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(CThostFtdcSPBMFutureParameterField obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected static long swigRelease(CThostFtdcSPBMFutureParameterField obj) {
    long ptr = 0;
    if (obj != null) {
      if (!obj.swigCMemOwn)
        throw new RuntimeException("Cannot release ownership as memory is not owned");
      ptr = obj.swigCPtr;
      obj.swigCMemOwn = false;
      obj.delete();
    }
    return ptr;
  }

  @SuppressWarnings("deprecation")
  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        thosttraderapiJNI.delete_CThostFtdcSPBMFutureParameterField(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public void setTradingDay(String value) {
    thosttraderapiJNI.CThostFtdcSPBMFutureParameterField_TradingDay_set(swigCPtr, this, value);
  }

  public String getTradingDay() {
    return thosttraderapiJNI.CThostFtdcSPBMFutureParameterField_TradingDay_get(swigCPtr, this);
  }

  public void setExchangeID(String value) {
    thosttraderapiJNI.CThostFtdcSPBMFutureParameterField_ExchangeID_set(swigCPtr, this, value);
  }

  public String getExchangeID() {
    return thosttraderapiJNI.CThostFtdcSPBMFutureParameterField_ExchangeID_get(swigCPtr, this);
  }

  public void setInstrumentID(String value) {
    thosttraderapiJNI.CThostFtdcSPBMFutureParameterField_InstrumentID_set(swigCPtr, this, value);
  }

  public String getInstrumentID() {
    return thosttraderapiJNI.CThostFtdcSPBMFutureParameterField_InstrumentID_get(swigCPtr, this);
  }

  public void setProdFamilyCode(String value) {
    thosttraderapiJNI.CThostFtdcSPBMFutureParameterField_ProdFamilyCode_set(swigCPtr, this, value);
  }

  public String getProdFamilyCode() {
    return thosttraderapiJNI.CThostFtdcSPBMFutureParameterField_ProdFamilyCode_get(swigCPtr, this);
  }

  public void setCvf(int value) {
    thosttraderapiJNI.CThostFtdcSPBMFutureParameterField_Cvf_set(swigCPtr, this, value);
  }

  public int getCvf() {
    return thosttraderapiJNI.CThostFtdcSPBMFutureParameterField_Cvf_get(swigCPtr, this);
  }

  public void setTimeRange(char value) {
    thosttraderapiJNI.CThostFtdcSPBMFutureParameterField_TimeRange_set(swigCPtr, this, value);
  }

  public char getTimeRange() {
    return thosttraderapiJNI.CThostFtdcSPBMFutureParameterField_TimeRange_get(swigCPtr, this);
  }

  public void setMarginRate(double value) {
    thosttraderapiJNI.CThostFtdcSPBMFutureParameterField_MarginRate_set(swigCPtr, this, value);
  }

  public double getMarginRate() {
    return thosttraderapiJNI.CThostFtdcSPBMFutureParameterField_MarginRate_get(swigCPtr, this);
  }

  public void setLockRateX(double value) {
    thosttraderapiJNI.CThostFtdcSPBMFutureParameterField_LockRateX_set(swigCPtr, this, value);
  }

  public double getLockRateX() {
    return thosttraderapiJNI.CThostFtdcSPBMFutureParameterField_LockRateX_get(swigCPtr, this);
  }

  public void setAddOnRate(double value) {
    thosttraderapiJNI.CThostFtdcSPBMFutureParameterField_AddOnRate_set(swigCPtr, this, value);
  }

  public double getAddOnRate() {
    return thosttraderapiJNI.CThostFtdcSPBMFutureParameterField_AddOnRate_get(swigCPtr, this);
  }

  public void setPreSettlementPrice(double value) {
    thosttraderapiJNI.CThostFtdcSPBMFutureParameterField_PreSettlementPrice_set(swigCPtr, this, value);
  }

  public double getPreSettlementPrice() {
    return thosttraderapiJNI.CThostFtdcSPBMFutureParameterField_PreSettlementPrice_get(swigCPtr, this);
  }

  public CThostFtdcSPBMFutureParameterField() {
    this(thosttraderapiJNI.new_CThostFtdcSPBMFutureParameterField(), true);
  }

}
