/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (https://www.swig.org).
 * Version 4.1.1
 *
 * Do not make changes to this file unless you know what you are doing - modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package com.quickhot.ctp.api;

public class CThostFtdcFutureLimitPosiParamField {
  private transient long swigCPtr;
  protected transient boolean swigCMemOwn;

  protected CThostFtdcFutureLimitPosiParamField(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(CThostFtdcFutureLimitPosiParamField obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected static long swigRelease(CThostFtdcFutureLimitPosiParamField obj) {
    long ptr = 0;
    if (obj != null) {
      if (!obj.swigCMemOwn)
        throw new RuntimeException("Cannot release ownership as memory is not owned");
      ptr = obj.swigCPtr;
      obj.swigCMemOwn = false;
      obj.delete();
    }
    return ptr;
  }

  @SuppressWarnings("deprecation")
  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        thosttraderapiJNI.delete_CThostFtdcFutureLimitPosiParamField(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public void setInvestorRange(char value) {
    thosttraderapiJNI.CThostFtdcFutureLimitPosiParamField_InvestorRange_set(swigCPtr, this, value);
  }

  public char getInvestorRange() {
    return thosttraderapiJNI.CThostFtdcFutureLimitPosiParamField_InvestorRange_get(swigCPtr, this);
  }

  public void setBrokerID(String value) {
    thosttraderapiJNI.CThostFtdcFutureLimitPosiParamField_BrokerID_set(swigCPtr, this, value);
  }

  public String getBrokerID() {
    return thosttraderapiJNI.CThostFtdcFutureLimitPosiParamField_BrokerID_get(swigCPtr, this);
  }

  public void setInvestorID(String value) {
    thosttraderapiJNI.CThostFtdcFutureLimitPosiParamField_InvestorID_set(swigCPtr, this, value);
  }

  public String getInvestorID() {
    return thosttraderapiJNI.CThostFtdcFutureLimitPosiParamField_InvestorID_get(swigCPtr, this);
  }

  public void setReserve1(String value) {
    thosttraderapiJNI.CThostFtdcFutureLimitPosiParamField_reserve1_set(swigCPtr, this, value);
  }

  public String getReserve1() {
    return thosttraderapiJNI.CThostFtdcFutureLimitPosiParamField_reserve1_get(swigCPtr, this);
  }

  public void setSpecOpenVolume(int value) {
    thosttraderapiJNI.CThostFtdcFutureLimitPosiParamField_SpecOpenVolume_set(swigCPtr, this, value);
  }

  public int getSpecOpenVolume() {
    return thosttraderapiJNI.CThostFtdcFutureLimitPosiParamField_SpecOpenVolume_get(swigCPtr, this);
  }

  public void setArbiOpenVolume(int value) {
    thosttraderapiJNI.CThostFtdcFutureLimitPosiParamField_ArbiOpenVolume_set(swigCPtr, this, value);
  }

  public int getArbiOpenVolume() {
    return thosttraderapiJNI.CThostFtdcFutureLimitPosiParamField_ArbiOpenVolume_get(swigCPtr, this);
  }

  public void setOpenVolume(int value) {
    thosttraderapiJNI.CThostFtdcFutureLimitPosiParamField_OpenVolume_set(swigCPtr, this, value);
  }

  public int getOpenVolume() {
    return thosttraderapiJNI.CThostFtdcFutureLimitPosiParamField_OpenVolume_get(swigCPtr, this);
  }

  public void setProductID(String value) {
    thosttraderapiJNI.CThostFtdcFutureLimitPosiParamField_ProductID_set(swigCPtr, this, value);
  }

  public String getProductID() {
    return thosttraderapiJNI.CThostFtdcFutureLimitPosiParamField_ProductID_get(swigCPtr, this);
  }

  public CThostFtdcFutureLimitPosiParamField() {
    this(thosttraderapiJNI.new_CThostFtdcFutureLimitPosiParamField(), true);
  }

}
