/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (https://www.swig.org).
 * Version 4.1.1
 *
 * Do not make changes to this file unless you know what you are doing - modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package com.quickhot.ctp.api;

public class CThostFtdcSyncDeltaInfoField {
  private transient long swigCPtr;
  protected transient boolean swigCMemOwn;

  protected CThostFtdcSyncDeltaInfoField(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(CThostFtdcSyncDeltaInfoField obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected static long swigRelease(CThostFtdcSyncDeltaInfoField obj) {
    long ptr = 0;
    if (obj != null) {
      if (!obj.swigCMemOwn)
        throw new RuntimeException("Cannot release ownership as memory is not owned");
      ptr = obj.swigCPtr;
      obj.swigCMemOwn = false;
      obj.delete();
    }
    return ptr;
  }

  @SuppressWarnings("deprecation")
  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        thosttraderapiJNI.delete_CThostFtdcSyncDeltaInfoField(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public void setSyncDeltaSequenceNo(int value) {
    thosttraderapiJNI.CThostFtdcSyncDeltaInfoField_SyncDeltaSequenceNo_set(swigCPtr, this, value);
  }

  public int getSyncDeltaSequenceNo() {
    return thosttraderapiJNI.CThostFtdcSyncDeltaInfoField_SyncDeltaSequenceNo_get(swigCPtr, this);
  }

  public void setSyncDeltaStatus(char value) {
    thosttraderapiJNI.CThostFtdcSyncDeltaInfoField_SyncDeltaStatus_set(swigCPtr, this, value);
  }

  public char getSyncDeltaStatus() {
    return thosttraderapiJNI.CThostFtdcSyncDeltaInfoField_SyncDeltaStatus_get(swigCPtr, this);
  }

  public void setSyncDescription(String value) {
    thosttraderapiJNI.CThostFtdcSyncDeltaInfoField_SyncDescription_set(swigCPtr, this, value);
  }

  public String getSyncDescription() {
    return thosttraderapiJNI.CThostFtdcSyncDeltaInfoField_SyncDescription_get(swigCPtr, this);
  }

  public void setIsOnlyTrdDelta(int value) {
    thosttraderapiJNI.CThostFtdcSyncDeltaInfoField_IsOnlyTrdDelta_set(swigCPtr, this, value);
  }

  public int getIsOnlyTrdDelta() {
    return thosttraderapiJNI.CThostFtdcSyncDeltaInfoField_IsOnlyTrdDelta_get(swigCPtr, this);
  }

  public CThostFtdcSyncDeltaInfoField() {
    this(thosttraderapiJNI.new_CThostFtdcSyncDeltaInfoField(), true);
  }

}
