/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (https://www.swig.org).
 * Version 4.1.1
 *
 * Do not make changes to this file unless you know what you are doing - modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package com.quickhot.ctp.api;

public class CThostFtdcAccountPropertyField {
  private transient long swigCPtr;
  protected transient boolean swigCMemOwn;

  protected CThostFtdcAccountPropertyField(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(CThostFtdcAccountPropertyField obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected static long swigRelease(CThostFtdcAccountPropertyField obj) {
    long ptr = 0;
    if (obj != null) {
      if (!obj.swigCMemOwn)
        throw new RuntimeException("Cannot release ownership as memory is not owned");
      ptr = obj.swigCPtr;
      obj.swigCMemOwn = false;
      obj.delete();
    }
    return ptr;
  }

  @SuppressWarnings("deprecation")
  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        thosttraderapiJNI.delete_CThostFtdcAccountPropertyField(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public void setBrokerID(String value) {
    thosttraderapiJNI.CThostFtdcAccountPropertyField_BrokerID_set(swigCPtr, this, value);
  }

  public String getBrokerID() {
    return thosttraderapiJNI.CThostFtdcAccountPropertyField_BrokerID_get(swigCPtr, this);
  }

  public void setAccountID(String value) {
    thosttraderapiJNI.CThostFtdcAccountPropertyField_AccountID_set(swigCPtr, this, value);
  }

  public String getAccountID() {
    return thosttraderapiJNI.CThostFtdcAccountPropertyField_AccountID_get(swigCPtr, this);
  }

  public void setBankID(String value) {
    thosttraderapiJNI.CThostFtdcAccountPropertyField_BankID_set(swigCPtr, this, value);
  }

  public String getBankID() {
    return thosttraderapiJNI.CThostFtdcAccountPropertyField_BankID_get(swigCPtr, this);
  }

  public void setBankAccount(String value) {
    thosttraderapiJNI.CThostFtdcAccountPropertyField_BankAccount_set(swigCPtr, this, value);
  }

  public String getBankAccount() {
    return thosttraderapiJNI.CThostFtdcAccountPropertyField_BankAccount_get(swigCPtr, this);
  }

  public void setOpenName(String value) {
    thosttraderapiJNI.CThostFtdcAccountPropertyField_OpenName_set(swigCPtr, this, value);
  }

  public String getOpenName() {
    return thosttraderapiJNI.CThostFtdcAccountPropertyField_OpenName_get(swigCPtr, this);
  }

  public void setOpenBank(String value) {
    thosttraderapiJNI.CThostFtdcAccountPropertyField_OpenBank_set(swigCPtr, this, value);
  }

  public String getOpenBank() {
    return thosttraderapiJNI.CThostFtdcAccountPropertyField_OpenBank_get(swigCPtr, this);
  }

  public void setIsActive(int value) {
    thosttraderapiJNI.CThostFtdcAccountPropertyField_IsActive_set(swigCPtr, this, value);
  }

  public int getIsActive() {
    return thosttraderapiJNI.CThostFtdcAccountPropertyField_IsActive_get(swigCPtr, this);
  }

  public void setAccountSourceType(char value) {
    thosttraderapiJNI.CThostFtdcAccountPropertyField_AccountSourceType_set(swigCPtr, this, value);
  }

  public char getAccountSourceType() {
    return thosttraderapiJNI.CThostFtdcAccountPropertyField_AccountSourceType_get(swigCPtr, this);
  }

  public void setOpenDate(String value) {
    thosttraderapiJNI.CThostFtdcAccountPropertyField_OpenDate_set(swigCPtr, this, value);
  }

  public String getOpenDate() {
    return thosttraderapiJNI.CThostFtdcAccountPropertyField_OpenDate_get(swigCPtr, this);
  }

  public void setCancelDate(String value) {
    thosttraderapiJNI.CThostFtdcAccountPropertyField_CancelDate_set(swigCPtr, this, value);
  }

  public String getCancelDate() {
    return thosttraderapiJNI.CThostFtdcAccountPropertyField_CancelDate_get(swigCPtr, this);
  }

  public void setOperatorID(String value) {
    thosttraderapiJNI.CThostFtdcAccountPropertyField_OperatorID_set(swigCPtr, this, value);
  }

  public String getOperatorID() {
    return thosttraderapiJNI.CThostFtdcAccountPropertyField_OperatorID_get(swigCPtr, this);
  }

  public void setOperateDate(String value) {
    thosttraderapiJNI.CThostFtdcAccountPropertyField_OperateDate_set(swigCPtr, this, value);
  }

  public String getOperateDate() {
    return thosttraderapiJNI.CThostFtdcAccountPropertyField_OperateDate_get(swigCPtr, this);
  }

  public void setOperateTime(String value) {
    thosttraderapiJNI.CThostFtdcAccountPropertyField_OperateTime_set(swigCPtr, this, value);
  }

  public String getOperateTime() {
    return thosttraderapiJNI.CThostFtdcAccountPropertyField_OperateTime_get(swigCPtr, this);
  }

  public void setCurrencyID(String value) {
    thosttraderapiJNI.CThostFtdcAccountPropertyField_CurrencyID_set(swigCPtr, this, value);
  }

  public String getCurrencyID() {
    return thosttraderapiJNI.CThostFtdcAccountPropertyField_CurrencyID_get(swigCPtr, this);
  }

  public CThostFtdcAccountPropertyField() {
    this(thosttraderapiJNI.new_CThostFtdcAccountPropertyField(), true);
  }

}
