/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (https://www.swig.org).
 * Version 4.1.1
 *
 * Do not make changes to this file unless you know what you are doing - modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package com.quickhot.ctp.api;

public class CThostFtdcInvestorField {
  private transient long swigCPtr;
  protected transient boolean swigCMemOwn;

  protected CThostFtdcInvestorField(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(CThostFtdcInvestorField obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected static long swigRelease(CThostFtdcInvestorField obj) {
    long ptr = 0;
    if (obj != null) {
      if (!obj.swigCMemOwn)
        throw new RuntimeException("Cannot release ownership as memory is not owned");
      ptr = obj.swigCPtr;
      obj.swigCMemOwn = false;
      obj.delete();
    }
    return ptr;
  }

  @SuppressWarnings("deprecation")
  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        thosttraderapiJNI.delete_CThostFtdcInvestorField(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public void setInvestorID(String value) {
    thosttraderapiJNI.CThostFtdcInvestorField_InvestorID_set(swigCPtr, this, value);
  }

  public String getInvestorID() {
    return thosttraderapiJNI.CThostFtdcInvestorField_InvestorID_get(swigCPtr, this);
  }

  public void setBrokerID(String value) {
    thosttraderapiJNI.CThostFtdcInvestorField_BrokerID_set(swigCPtr, this, value);
  }

  public String getBrokerID() {
    return thosttraderapiJNI.CThostFtdcInvestorField_BrokerID_get(swigCPtr, this);
  }

  public void setInvestorGroupID(String value) {
    thosttraderapiJNI.CThostFtdcInvestorField_InvestorGroupID_set(swigCPtr, this, value);
  }

  public String getInvestorGroupID() {
    return thosttraderapiJNI.CThostFtdcInvestorField_InvestorGroupID_get(swigCPtr, this);
  }

  public void setInvestorName(String value) {
    thosttraderapiJNI.CThostFtdcInvestorField_InvestorName_set(swigCPtr, this, value);
  }

  public String getInvestorName() {
    return thosttraderapiJNI.CThostFtdcInvestorField_InvestorName_get(swigCPtr, this);
  }

  public void setIdentifiedCardType(char value) {
    thosttraderapiJNI.CThostFtdcInvestorField_IdentifiedCardType_set(swigCPtr, this, value);
  }

  public char getIdentifiedCardType() {
    return thosttraderapiJNI.CThostFtdcInvestorField_IdentifiedCardType_get(swigCPtr, this);
  }

  public void setIdentifiedCardNo(String value) {
    thosttraderapiJNI.CThostFtdcInvestorField_IdentifiedCardNo_set(swigCPtr, this, value);
  }

  public String getIdentifiedCardNo() {
    return thosttraderapiJNI.CThostFtdcInvestorField_IdentifiedCardNo_get(swigCPtr, this);
  }

  public void setIsActive(int value) {
    thosttraderapiJNI.CThostFtdcInvestorField_IsActive_set(swigCPtr, this, value);
  }

  public int getIsActive() {
    return thosttraderapiJNI.CThostFtdcInvestorField_IsActive_get(swigCPtr, this);
  }

  public void setTelephone(String value) {
    thosttraderapiJNI.CThostFtdcInvestorField_Telephone_set(swigCPtr, this, value);
  }

  public String getTelephone() {
    return thosttraderapiJNI.CThostFtdcInvestorField_Telephone_get(swigCPtr, this);
  }

  public void setAddress(String value) {
    thosttraderapiJNI.CThostFtdcInvestorField_Address_set(swigCPtr, this, value);
  }

  public String getAddress() {
    return thosttraderapiJNI.CThostFtdcInvestorField_Address_get(swigCPtr, this);
  }

  public void setOpenDate(String value) {
    thosttraderapiJNI.CThostFtdcInvestorField_OpenDate_set(swigCPtr, this, value);
  }

  public String getOpenDate() {
    return thosttraderapiJNI.CThostFtdcInvestorField_OpenDate_get(swigCPtr, this);
  }

  public void setMobile(String value) {
    thosttraderapiJNI.CThostFtdcInvestorField_Mobile_set(swigCPtr, this, value);
  }

  public String getMobile() {
    return thosttraderapiJNI.CThostFtdcInvestorField_Mobile_get(swigCPtr, this);
  }

  public void setCommModelID(String value) {
    thosttraderapiJNI.CThostFtdcInvestorField_CommModelID_set(swigCPtr, this, value);
  }

  public String getCommModelID() {
    return thosttraderapiJNI.CThostFtdcInvestorField_CommModelID_get(swigCPtr, this);
  }

  public void setMarginModelID(String value) {
    thosttraderapiJNI.CThostFtdcInvestorField_MarginModelID_set(swigCPtr, this, value);
  }

  public String getMarginModelID() {
    return thosttraderapiJNI.CThostFtdcInvestorField_MarginModelID_get(swigCPtr, this);
  }

  public void setIsOrderFreq(char value) {
    thosttraderapiJNI.CThostFtdcInvestorField_IsOrderFreq_set(swigCPtr, this, value);
  }

  public char getIsOrderFreq() {
    return thosttraderapiJNI.CThostFtdcInvestorField_IsOrderFreq_get(swigCPtr, this);
  }

  public void setIsOpenVolLimit(char value) {
    thosttraderapiJNI.CThostFtdcInvestorField_IsOpenVolLimit_set(swigCPtr, this, value);
  }

  public char getIsOpenVolLimit() {
    return thosttraderapiJNI.CThostFtdcInvestorField_IsOpenVolLimit_get(swigCPtr, this);
  }

  public CThostFtdcInvestorField() {
    this(thosttraderapiJNI.new_CThostFtdcInvestorField(), true);
  }

}
