/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (https://www.swig.org).
 * Version 4.1.1
 *
 * Do not make changes to this file unless you know what you are doing - modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package com.quickhot.ctp.api;

public class CThostFtdcSPBMPortfDefinitionField {
  private transient long swigCPtr;
  protected transient boolean swigCMemOwn;

  protected CThostFtdcSPBMPortfDefinitionField(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(CThostFtdcSPBMPortfDefinitionField obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected static long swigRelease(CThostFtdcSPBMPortfDefinitionField obj) {
    long ptr = 0;
    if (obj != null) {
      if (!obj.swigCMemOwn)
        throw new RuntimeException("Cannot release ownership as memory is not owned");
      ptr = obj.swigCPtr;
      obj.swigCMemOwn = false;
      obj.delete();
    }
    return ptr;
  }

  @SuppressWarnings("deprecation")
  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        thosttraderapiJNI.delete_CThostFtdcSPBMPortfDefinitionField(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public void setExchangeID(String value) {
    thosttraderapiJNI.CThostFtdcSPBMPortfDefinitionField_ExchangeID_set(swigCPtr, this, value);
  }

  public String getExchangeID() {
    return thosttraderapiJNI.CThostFtdcSPBMPortfDefinitionField_ExchangeID_get(swigCPtr, this);
  }

  public void setPortfolioDefID(int value) {
    thosttraderapiJNI.CThostFtdcSPBMPortfDefinitionField_PortfolioDefID_set(swigCPtr, this, value);
  }

  public int getPortfolioDefID() {
    return thosttraderapiJNI.CThostFtdcSPBMPortfDefinitionField_PortfolioDefID_get(swigCPtr, this);
  }

  public void setProdFamilyCode(String value) {
    thosttraderapiJNI.CThostFtdcSPBMPortfDefinitionField_ProdFamilyCode_set(swigCPtr, this, value);
  }

  public String getProdFamilyCode() {
    return thosttraderapiJNI.CThostFtdcSPBMPortfDefinitionField_ProdFamilyCode_get(swigCPtr, this);
  }

  public void setIsSPBM(int value) {
    thosttraderapiJNI.CThostFtdcSPBMPortfDefinitionField_IsSPBM_set(swigCPtr, this, value);
  }

  public int getIsSPBM() {
    return thosttraderapiJNI.CThostFtdcSPBMPortfDefinitionField_IsSPBM_get(swigCPtr, this);
  }

  public CThostFtdcSPBMPortfDefinitionField() {
    this(thosttraderapiJNI.new_CThostFtdcSPBMPortfDefinitionField(), true);
  }

}
