/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (https://www.swig.org).
 * Version 4.1.1
 *
 * Do not make changes to this file unless you know what you are doing - modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package com.quickhot.ctp.api;

public class CThostFtdcMulticastInstrumentField {
  private transient long swigCPtr;
  protected transient boolean swigCMemOwn;

  protected CThostFtdcMulticastInstrumentField(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(CThostFtdcMulticastInstrumentField obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected static long swigRelease(CThostFtdcMulticastInstrumentField obj) {
    long ptr = 0;
    if (obj != null) {
      if (!obj.swigCMemOwn)
        throw new RuntimeException("Cannot release ownership as memory is not owned");
      ptr = obj.swigCPtr;
      obj.swigCMemOwn = false;
      obj.delete();
    }
    return ptr;
  }

  @SuppressWarnings("deprecation")
  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        thosttraderapiJNI.delete_CThostFtdcMulticastInstrumentField(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public void setTopicID(int value) {
    thosttraderapiJNI.CThostFtdcMulticastInstrumentField_TopicID_set(swigCPtr, this, value);
  }

  public int getTopicID() {
    return thosttraderapiJNI.CThostFtdcMulticastInstrumentField_TopicID_get(swigCPtr, this);
  }

  public void setReserve1(String value) {
    thosttraderapiJNI.CThostFtdcMulticastInstrumentField_reserve1_set(swigCPtr, this, value);
  }

  public String getReserve1() {
    return thosttraderapiJNI.CThostFtdcMulticastInstrumentField_reserve1_get(swigCPtr, this);
  }

  public void setInstrumentNo(int value) {
    thosttraderapiJNI.CThostFtdcMulticastInstrumentField_InstrumentNo_set(swigCPtr, this, value);
  }

  public int getInstrumentNo() {
    return thosttraderapiJNI.CThostFtdcMulticastInstrumentField_InstrumentNo_get(swigCPtr, this);
  }

  public void setCodePrice(double value) {
    thosttraderapiJNI.CThostFtdcMulticastInstrumentField_CodePrice_set(swigCPtr, this, value);
  }

  public double getCodePrice() {
    return thosttraderapiJNI.CThostFtdcMulticastInstrumentField_CodePrice_get(swigCPtr, this);
  }

  public void setVolumeMultiple(int value) {
    thosttraderapiJNI.CThostFtdcMulticastInstrumentField_VolumeMultiple_set(swigCPtr, this, value);
  }

  public int getVolumeMultiple() {
    return thosttraderapiJNI.CThostFtdcMulticastInstrumentField_VolumeMultiple_get(swigCPtr, this);
  }

  public void setPriceTick(double value) {
    thosttraderapiJNI.CThostFtdcMulticastInstrumentField_PriceTick_set(swigCPtr, this, value);
  }

  public double getPriceTick() {
    return thosttraderapiJNI.CThostFtdcMulticastInstrumentField_PriceTick_get(swigCPtr, this);
  }

  public void setInstrumentID(String value) {
    thosttraderapiJNI.CThostFtdcMulticastInstrumentField_InstrumentID_set(swigCPtr, this, value);
  }

  public String getInstrumentID() {
    return thosttraderapiJNI.CThostFtdcMulticastInstrumentField_InstrumentID_get(swigCPtr, this);
  }

  public CThostFtdcMulticastInstrumentField() {
    this(thosttraderapiJNI.new_CThostFtdcMulticastInstrumentField(), true);
  }

}
