/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (https://www.swig.org).
 * Version 4.1.1
 *
 * Do not make changes to this file unless you know what you are doing - modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package com.quickhot.ctp.api;

public class CThostFtdcSyncDeltaTradingAccountField {
  private transient long swigCPtr;
  protected transient boolean swigCMemOwn;

  protected CThostFtdcSyncDeltaTradingAccountField(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(CThostFtdcSyncDeltaTradingAccountField obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected static long swigRelease(CThostFtdcSyncDeltaTradingAccountField obj) {
    long ptr = 0;
    if (obj != null) {
      if (!obj.swigCMemOwn)
        throw new RuntimeException("Cannot release ownership as memory is not owned");
      ptr = obj.swigCPtr;
      obj.swigCMemOwn = false;
      obj.delete();
    }
    return ptr;
  }

  @SuppressWarnings("deprecation")
  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        thosttraderapiJNI.delete_CThostFtdcSyncDeltaTradingAccountField(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public void setBrokerID(String value) {
    thosttraderapiJNI.CThostFtdcSyncDeltaTradingAccountField_BrokerID_set(swigCPtr, this, value);
  }

  public String getBrokerID() {
    return thosttraderapiJNI.CThostFtdcSyncDeltaTradingAccountField_BrokerID_get(swigCPtr, this);
  }

  public void setAccountID(String value) {
    thosttraderapiJNI.CThostFtdcSyncDeltaTradingAccountField_AccountID_set(swigCPtr, this, value);
  }

  public String getAccountID() {
    return thosttraderapiJNI.CThostFtdcSyncDeltaTradingAccountField_AccountID_get(swigCPtr, this);
  }

  public void setPreMortgage(double value) {
    thosttraderapiJNI.CThostFtdcSyncDeltaTradingAccountField_PreMortgage_set(swigCPtr, this, value);
  }

  public double getPreMortgage() {
    return thosttraderapiJNI.CThostFtdcSyncDeltaTradingAccountField_PreMortgage_get(swigCPtr, this);
  }

  public void setPreCredit(double value) {
    thosttraderapiJNI.CThostFtdcSyncDeltaTradingAccountField_PreCredit_set(swigCPtr, this, value);
  }

  public double getPreCredit() {
    return thosttraderapiJNI.CThostFtdcSyncDeltaTradingAccountField_PreCredit_get(swigCPtr, this);
  }

  public void setPreDeposit(double value) {
    thosttraderapiJNI.CThostFtdcSyncDeltaTradingAccountField_PreDeposit_set(swigCPtr, this, value);
  }

  public double getPreDeposit() {
    return thosttraderapiJNI.CThostFtdcSyncDeltaTradingAccountField_PreDeposit_get(swigCPtr, this);
  }

  public void setPreBalance(double value) {
    thosttraderapiJNI.CThostFtdcSyncDeltaTradingAccountField_PreBalance_set(swigCPtr, this, value);
  }

  public double getPreBalance() {
    return thosttraderapiJNI.CThostFtdcSyncDeltaTradingAccountField_PreBalance_get(swigCPtr, this);
  }

  public void setPreMargin(double value) {
    thosttraderapiJNI.CThostFtdcSyncDeltaTradingAccountField_PreMargin_set(swigCPtr, this, value);
  }

  public double getPreMargin() {
    return thosttraderapiJNI.CThostFtdcSyncDeltaTradingAccountField_PreMargin_get(swigCPtr, this);
  }

  public void setInterestBase(double value) {
    thosttraderapiJNI.CThostFtdcSyncDeltaTradingAccountField_InterestBase_set(swigCPtr, this, value);
  }

  public double getInterestBase() {
    return thosttraderapiJNI.CThostFtdcSyncDeltaTradingAccountField_InterestBase_get(swigCPtr, this);
  }

  public void setInterest(double value) {
    thosttraderapiJNI.CThostFtdcSyncDeltaTradingAccountField_Interest_set(swigCPtr, this, value);
  }

  public double getInterest() {
    return thosttraderapiJNI.CThostFtdcSyncDeltaTradingAccountField_Interest_get(swigCPtr, this);
  }

  public void setDeposit(double value) {
    thosttraderapiJNI.CThostFtdcSyncDeltaTradingAccountField_Deposit_set(swigCPtr, this, value);
  }

  public double getDeposit() {
    return thosttraderapiJNI.CThostFtdcSyncDeltaTradingAccountField_Deposit_get(swigCPtr, this);
  }

  public void setWithdraw(double value) {
    thosttraderapiJNI.CThostFtdcSyncDeltaTradingAccountField_Withdraw_set(swigCPtr, this, value);
  }

  public double getWithdraw() {
    return thosttraderapiJNI.CThostFtdcSyncDeltaTradingAccountField_Withdraw_get(swigCPtr, this);
  }

  public void setFrozenMargin(double value) {
    thosttraderapiJNI.CThostFtdcSyncDeltaTradingAccountField_FrozenMargin_set(swigCPtr, this, value);
  }

  public double getFrozenMargin() {
    return thosttraderapiJNI.CThostFtdcSyncDeltaTradingAccountField_FrozenMargin_get(swigCPtr, this);
  }

  public void setFrozenCash(double value) {
    thosttraderapiJNI.CThostFtdcSyncDeltaTradingAccountField_FrozenCash_set(swigCPtr, this, value);
  }

  public double getFrozenCash() {
    return thosttraderapiJNI.CThostFtdcSyncDeltaTradingAccountField_FrozenCash_get(swigCPtr, this);
  }

  public void setFrozenCommission(double value) {
    thosttraderapiJNI.CThostFtdcSyncDeltaTradingAccountField_FrozenCommission_set(swigCPtr, this, value);
  }

  public double getFrozenCommission() {
    return thosttraderapiJNI.CThostFtdcSyncDeltaTradingAccountField_FrozenCommission_get(swigCPtr, this);
  }

  public void setCurrMargin(double value) {
    thosttraderapiJNI.CThostFtdcSyncDeltaTradingAccountField_CurrMargin_set(swigCPtr, this, value);
  }

  public double getCurrMargin() {
    return thosttraderapiJNI.CThostFtdcSyncDeltaTradingAccountField_CurrMargin_get(swigCPtr, this);
  }

  public void setCashIn(double value) {
    thosttraderapiJNI.CThostFtdcSyncDeltaTradingAccountField_CashIn_set(swigCPtr, this, value);
  }

  public double getCashIn() {
    return thosttraderapiJNI.CThostFtdcSyncDeltaTradingAccountField_CashIn_get(swigCPtr, this);
  }

  public void setCommission(double value) {
    thosttraderapiJNI.CThostFtdcSyncDeltaTradingAccountField_Commission_set(swigCPtr, this, value);
  }

  public double getCommission() {
    return thosttraderapiJNI.CThostFtdcSyncDeltaTradingAccountField_Commission_get(swigCPtr, this);
  }

  public void setCloseProfit(double value) {
    thosttraderapiJNI.CThostFtdcSyncDeltaTradingAccountField_CloseProfit_set(swigCPtr, this, value);
  }

  public double getCloseProfit() {
    return thosttraderapiJNI.CThostFtdcSyncDeltaTradingAccountField_CloseProfit_get(swigCPtr, this);
  }

  public void setPositionProfit(double value) {
    thosttraderapiJNI.CThostFtdcSyncDeltaTradingAccountField_PositionProfit_set(swigCPtr, this, value);
  }

  public double getPositionProfit() {
    return thosttraderapiJNI.CThostFtdcSyncDeltaTradingAccountField_PositionProfit_get(swigCPtr, this);
  }

  public void setBalance(double value) {
    thosttraderapiJNI.CThostFtdcSyncDeltaTradingAccountField_Balance_set(swigCPtr, this, value);
  }

  public double getBalance() {
    return thosttraderapiJNI.CThostFtdcSyncDeltaTradingAccountField_Balance_get(swigCPtr, this);
  }

  public void setAvailable(double value) {
    thosttraderapiJNI.CThostFtdcSyncDeltaTradingAccountField_Available_set(swigCPtr, this, value);
  }

  public double getAvailable() {
    return thosttraderapiJNI.CThostFtdcSyncDeltaTradingAccountField_Available_get(swigCPtr, this);
  }

  public void setWithdrawQuota(double value) {
    thosttraderapiJNI.CThostFtdcSyncDeltaTradingAccountField_WithdrawQuota_set(swigCPtr, this, value);
  }

  public double getWithdrawQuota() {
    return thosttraderapiJNI.CThostFtdcSyncDeltaTradingAccountField_WithdrawQuota_get(swigCPtr, this);
  }

  public void setReserve(double value) {
    thosttraderapiJNI.CThostFtdcSyncDeltaTradingAccountField_Reserve_set(swigCPtr, this, value);
  }

  public double getReserve() {
    return thosttraderapiJNI.CThostFtdcSyncDeltaTradingAccountField_Reserve_get(swigCPtr, this);
  }

  public void setTradingDay(String value) {
    thosttraderapiJNI.CThostFtdcSyncDeltaTradingAccountField_TradingDay_set(swigCPtr, this, value);
  }

  public String getTradingDay() {
    return thosttraderapiJNI.CThostFtdcSyncDeltaTradingAccountField_TradingDay_get(swigCPtr, this);
  }

  public void setSettlementID(int value) {
    thosttraderapiJNI.CThostFtdcSyncDeltaTradingAccountField_SettlementID_set(swigCPtr, this, value);
  }

  public int getSettlementID() {
    return thosttraderapiJNI.CThostFtdcSyncDeltaTradingAccountField_SettlementID_get(swigCPtr, this);
  }

  public void setCredit(double value) {
    thosttraderapiJNI.CThostFtdcSyncDeltaTradingAccountField_Credit_set(swigCPtr, this, value);
  }

  public double getCredit() {
    return thosttraderapiJNI.CThostFtdcSyncDeltaTradingAccountField_Credit_get(swigCPtr, this);
  }

  public void setMortgage(double value) {
    thosttraderapiJNI.CThostFtdcSyncDeltaTradingAccountField_Mortgage_set(swigCPtr, this, value);
  }

  public double getMortgage() {
    return thosttraderapiJNI.CThostFtdcSyncDeltaTradingAccountField_Mortgage_get(swigCPtr, this);
  }

  public void setExchangeMargin(double value) {
    thosttraderapiJNI.CThostFtdcSyncDeltaTradingAccountField_ExchangeMargin_set(swigCPtr, this, value);
  }

  public double getExchangeMargin() {
    return thosttraderapiJNI.CThostFtdcSyncDeltaTradingAccountField_ExchangeMargin_get(swigCPtr, this);
  }

  public void setDeliveryMargin(double value) {
    thosttraderapiJNI.CThostFtdcSyncDeltaTradingAccountField_DeliveryMargin_set(swigCPtr, this, value);
  }

  public double getDeliveryMargin() {
    return thosttraderapiJNI.CThostFtdcSyncDeltaTradingAccountField_DeliveryMargin_get(swigCPtr, this);
  }

  public void setExchangeDeliveryMargin(double value) {
    thosttraderapiJNI.CThostFtdcSyncDeltaTradingAccountField_ExchangeDeliveryMargin_set(swigCPtr, this, value);
  }

  public double getExchangeDeliveryMargin() {
    return thosttraderapiJNI.CThostFtdcSyncDeltaTradingAccountField_ExchangeDeliveryMargin_get(swigCPtr, this);
  }

  public void setReserveBalance(double value) {
    thosttraderapiJNI.CThostFtdcSyncDeltaTradingAccountField_ReserveBalance_set(swigCPtr, this, value);
  }

  public double getReserveBalance() {
    return thosttraderapiJNI.CThostFtdcSyncDeltaTradingAccountField_ReserveBalance_get(swigCPtr, this);
  }

  public void setCurrencyID(String value) {
    thosttraderapiJNI.CThostFtdcSyncDeltaTradingAccountField_CurrencyID_set(swigCPtr, this, value);
  }

  public String getCurrencyID() {
    return thosttraderapiJNI.CThostFtdcSyncDeltaTradingAccountField_CurrencyID_get(swigCPtr, this);
  }

  public void setPreFundMortgageIn(double value) {
    thosttraderapiJNI.CThostFtdcSyncDeltaTradingAccountField_PreFundMortgageIn_set(swigCPtr, this, value);
  }

  public double getPreFundMortgageIn() {
    return thosttraderapiJNI.CThostFtdcSyncDeltaTradingAccountField_PreFundMortgageIn_get(swigCPtr, this);
  }

  public void setPreFundMortgageOut(double value) {
    thosttraderapiJNI.CThostFtdcSyncDeltaTradingAccountField_PreFundMortgageOut_set(swigCPtr, this, value);
  }

  public double getPreFundMortgageOut() {
    return thosttraderapiJNI.CThostFtdcSyncDeltaTradingAccountField_PreFundMortgageOut_get(swigCPtr, this);
  }

  public void setFundMortgageIn(double value) {
    thosttraderapiJNI.CThostFtdcSyncDeltaTradingAccountField_FundMortgageIn_set(swigCPtr, this, value);
  }

  public double getFundMortgageIn() {
    return thosttraderapiJNI.CThostFtdcSyncDeltaTradingAccountField_FundMortgageIn_get(swigCPtr, this);
  }

  public void setFundMortgageOut(double value) {
    thosttraderapiJNI.CThostFtdcSyncDeltaTradingAccountField_FundMortgageOut_set(swigCPtr, this, value);
  }

  public double getFundMortgageOut() {
    return thosttraderapiJNI.CThostFtdcSyncDeltaTradingAccountField_FundMortgageOut_get(swigCPtr, this);
  }

  public void setFundMortgageAvailable(double value) {
    thosttraderapiJNI.CThostFtdcSyncDeltaTradingAccountField_FundMortgageAvailable_set(swigCPtr, this, value);
  }

  public double getFundMortgageAvailable() {
    return thosttraderapiJNI.CThostFtdcSyncDeltaTradingAccountField_FundMortgageAvailable_get(swigCPtr, this);
  }

  public void setMortgageableFund(double value) {
    thosttraderapiJNI.CThostFtdcSyncDeltaTradingAccountField_MortgageableFund_set(swigCPtr, this, value);
  }

  public double getMortgageableFund() {
    return thosttraderapiJNI.CThostFtdcSyncDeltaTradingAccountField_MortgageableFund_get(swigCPtr, this);
  }

  public void setSpecProductMargin(double value) {
    thosttraderapiJNI.CThostFtdcSyncDeltaTradingAccountField_SpecProductMargin_set(swigCPtr, this, value);
  }

  public double getSpecProductMargin() {
    return thosttraderapiJNI.CThostFtdcSyncDeltaTradingAccountField_SpecProductMargin_get(swigCPtr, this);
  }

  public void setSpecProductFrozenMargin(double value) {
    thosttraderapiJNI.CThostFtdcSyncDeltaTradingAccountField_SpecProductFrozenMargin_set(swigCPtr, this, value);
  }

  public double getSpecProductFrozenMargin() {
    return thosttraderapiJNI.CThostFtdcSyncDeltaTradingAccountField_SpecProductFrozenMargin_get(swigCPtr, this);
  }

  public void setSpecProductCommission(double value) {
    thosttraderapiJNI.CThostFtdcSyncDeltaTradingAccountField_SpecProductCommission_set(swigCPtr, this, value);
  }

  public double getSpecProductCommission() {
    return thosttraderapiJNI.CThostFtdcSyncDeltaTradingAccountField_SpecProductCommission_get(swigCPtr, this);
  }

  public void setSpecProductFrozenCommission(double value) {
    thosttraderapiJNI.CThostFtdcSyncDeltaTradingAccountField_SpecProductFrozenCommission_set(swigCPtr, this, value);
  }

  public double getSpecProductFrozenCommission() {
    return thosttraderapiJNI.CThostFtdcSyncDeltaTradingAccountField_SpecProductFrozenCommission_get(swigCPtr, this);
  }

  public void setSpecProductPositionProfit(double value) {
    thosttraderapiJNI.CThostFtdcSyncDeltaTradingAccountField_SpecProductPositionProfit_set(swigCPtr, this, value);
  }

  public double getSpecProductPositionProfit() {
    return thosttraderapiJNI.CThostFtdcSyncDeltaTradingAccountField_SpecProductPositionProfit_get(swigCPtr, this);
  }

  public void setSpecProductCloseProfit(double value) {
    thosttraderapiJNI.CThostFtdcSyncDeltaTradingAccountField_SpecProductCloseProfit_set(swigCPtr, this, value);
  }

  public double getSpecProductCloseProfit() {
    return thosttraderapiJNI.CThostFtdcSyncDeltaTradingAccountField_SpecProductCloseProfit_get(swigCPtr, this);
  }

  public void setSpecProductPositionProfitByAlg(double value) {
    thosttraderapiJNI.CThostFtdcSyncDeltaTradingAccountField_SpecProductPositionProfitByAlg_set(swigCPtr, this, value);
  }

  public double getSpecProductPositionProfitByAlg() {
    return thosttraderapiJNI.CThostFtdcSyncDeltaTradingAccountField_SpecProductPositionProfitByAlg_get(swigCPtr, this);
  }

  public void setSpecProductExchangeMargin(double value) {
    thosttraderapiJNI.CThostFtdcSyncDeltaTradingAccountField_SpecProductExchangeMargin_set(swigCPtr, this, value);
  }

  public double getSpecProductExchangeMargin() {
    return thosttraderapiJNI.CThostFtdcSyncDeltaTradingAccountField_SpecProductExchangeMargin_get(swigCPtr, this);
  }

  public void setFrozenSwap(double value) {
    thosttraderapiJNI.CThostFtdcSyncDeltaTradingAccountField_FrozenSwap_set(swigCPtr, this, value);
  }

  public double getFrozenSwap() {
    return thosttraderapiJNI.CThostFtdcSyncDeltaTradingAccountField_FrozenSwap_get(swigCPtr, this);
  }

  public void setRemainSwap(double value) {
    thosttraderapiJNI.CThostFtdcSyncDeltaTradingAccountField_RemainSwap_set(swigCPtr, this, value);
  }

  public double getRemainSwap() {
    return thosttraderapiJNI.CThostFtdcSyncDeltaTradingAccountField_RemainSwap_get(swigCPtr, this);
  }

  public void setSyncDeltaSequenceNo(int value) {
    thosttraderapiJNI.CThostFtdcSyncDeltaTradingAccountField_SyncDeltaSequenceNo_set(swigCPtr, this, value);
  }

  public int getSyncDeltaSequenceNo() {
    return thosttraderapiJNI.CThostFtdcSyncDeltaTradingAccountField_SyncDeltaSequenceNo_get(swigCPtr, this);
  }

  public CThostFtdcSyncDeltaTradingAccountField() {
    this(thosttraderapiJNI.new_CThostFtdcSyncDeltaTradingAccountField(), true);
  }

}
